# Generated by Django 4.2.20 on 2025-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('website', models.URLField(blank=True, default='', null=True)),
                ('head_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('head_phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('head_email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campus/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
